// let peliculas = []
// listaPeliculas[0]=
//   "https://hips.hearstapps.com/hmg-prod/images/el-despertar-de-la-fuerza-1575448990.jpg",
// listaPeliculas[1]=
//   "https://images.cdn2.buscalibre.com/fit-in/360x360/5f/30/5f30570ba80ea985m/El_seanor_de_los_anillos_Las_dos_torres-660835653-large.jpg",
// listaPeliculas[2]=
//   "https://centrocomercialcamaretas.com/wp-content/uploads/2022/10/joker.jpg",

// for (let i = 0; i < 3; i = i + 1;) {
// document.write("<img src=" + listaPeliculas[0] + ">");

// };
var listaPeliculas = [
    "https://upload.wikimedia.org/wikipedia/pt/thumb/1/1b/Schoolrockposter.jpg/210px-Schoolrockposter.jpg",
    "https://1.bp.blogspot.com/-ImZPRqLsluE/WFK156_6pNI/AAAAAAAAYBY/0lEhNRF5wfQdLfr6hpT57_Jt2eBrE9H5wCLcB/s1600/arrival-kartoun-desert.jpg",
    "https://musicart.xboxlive.com/7/94fc5000-0000-0000-0000-000000000002/504/image.jpg",
    "https://upload.wikimedia.org/wikipedia/pt/7/76/10_Things_I_Hate_About_You.jpg",
    "https://br.web.img2.acsta.net/medias/nmedia/18/91/08/82/20128877.JPG",
  
    "https://i.pinimg.com/236x/f4/d7/24/f4d72491c0366c61b1d24912bc0a8079.jpg",
    "https://images.cdn2.buscalibre.com/fit-in/360x360/5f/30/5f30570ba80ea985abd0d8fcaeecc15a.jpg",
    "https://centrocomercialcamaretas.com/wp-content/uploads/2022/10/joker.jpg",
    "https://es.web.img3.acsta.net/pictures/22/10/04/16/26/1929878.jpg"
  ];
  
  // listaPeliculas[0] =
  //   "https://upload.wikimedia.org/wikipedia/pt/thumb/1/1b/Schoolrockposter.jpg/210px-Schoolrockposter.jpg";
  // listaPeliculas[1] =
  //   "https://1.bp.blogspot.com/-ImZPRqLsluE/WFK156_6pNI/AAAAAAAAYBY/0lEhNRF5wfQdLfr6hpT57_Jt2eBrE9H5wCLcB/s1600/arrival-kartoun-desert.jpg";
  // listaPeliculas[2] =
  //   "https://musicart.xboxlive.com/7/94fc5000-0000-0000-0000-000000000002/504/image.jpg";
  
  for (let i = 0; i < listaPeliculas.length; i++) {
    document.write("<img src=" + listaPeliculas[i] + ">");
  }
  
